spring:
  config:
    activate:
      on-profile : dev
  analysis:
    key: G_enut2BTuQK76_Nmb3KgtLPt-4mTmie
    secret: S-u7a0CPBNfUi7D_Ckys-MOoeEHeLXNl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sail106?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  hikari:
    maximum-pool-size: 50
    minimum-idle: 50
    connection-timeout: 5000
    connection-test-query: /*CONNECTION TEST QUERY*/SELECT NOW() FROM DUAL
    idle-timeout: 600000
    max-lifetime: 1800000
    auto-commit: true
    pool-name: DevLogHikariCP
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: flowering.service@gmail.com
    password: xuuwdlngsyyhqqqs
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true
  jwt:
    access: FLOWERINGACCESSKEYLOWERINGACCESSKEYLOWERINGACCESSKEY
    refresh: FLOWERINGREFRESHKEYFLOWERINGREFRESHKEYFLOWERINGREFRESHKEY
    accesstime: 86400000
    refreshtime: 604800000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 22e2b2f13382410c41cd0cdc617fe6ed
            client-secret: Gmh1INUTfN6XcgG6Y6i6Wg64UevpAbEt
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email, name, gender, birthday, birthyear

          naver:
            client-id: v_rtqOoNvQ0MkebpbnKz
            client-secret: s0UCuw4Eqq
            redirect-uri: http://localhost:8080/navercallback
            authorization-grant-type: authorization_code
            scope: email, nickname, profile_image, gender, name, birthday, birthyear
            client-name: Naver

          google:
            client-id: 676576305266-huk4p5l9tffnmp997qvvjmanfbjlohjv.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
iamport:
  key: 3730036181048481
  secret: AWDy8eyVev3rP46VrgPWdB5QLoJZmEGyPt6LOm6XdoO9piSF2d0Wf11hwPLjVuISZAB4iI2RWBM3YO3M
chatgpt :
  key : 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